FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS builder
WORKDIR /source

COPY *.csproj ./
RUN dotnet restore

COPY . .
RUN dotnet publish --output /app/ --configuration Release

FROM mcr.microsoft.com/dotnet/core/aspnet:8.0
WORKDIR /app
COPY --from=builder /app .
ENTRYPOINT ["dotnet", "Authors.dll"]